### ISSUE TITLE
final version of mockup

### ISSUE THREAD

**Issue by mdo91** [mdo91/Swe-573#11]
**The following image represents the mockup of learning platform**
![Mockup](https://github.com/mdo91/Swe-573/blob/master/final%20version.png)

**Comment by mdo91** [comment]
mockup has been updated due to some discussions that been held during the lecture

**Comment by uskudarli** [comment]
They look good to me! Ellerine saglik.

I encourage you to think of teaching material that is not so conventionally course room kinds of material. Especially you may think about reaching out to young people about ecological issues ,where you provide local examples that will be familiar to them.

**Comment by mdo91** [comment]
Tesekkurler hocam, i will take that into consideration.
